# Generated by Django 4.1.5 on 2023-01-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(through='app.PostCategory', to='app.category'),
        ),
    ]
