# Generated by Django 4.1.5 on 2023-01-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.AddField(
            model_name='response',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
